### ISSUE TITLE
Info blurb

### ISSUE THREAD

**Issue by jvcasillas** [learnB4SS/learnB4SS.github.io#2]
From Timo: 

"Draft:

"Our understanding of human speech is increasingly shaped by quantitative data. It is thus of critical importance to evaluate quantitative findings inferentially. This workshop aims at introducing Bayesian inference for the quantification of phonetic data. Following other scientific disciplines, the last decades where dominated by statistical inference within the null-hypothesis-significance-testing framework. This framework comes with many conceptual challenges and pitfalls, and comes with technical limitations that prevent us from analyzing our data in an appropriate way. More recently, many researchers have started to use an alternative inferential framework: Bayesian inference. Bayesian inference more closely answers the research questions we ask; it is much more flexible; and it allows us to run appropriate statistical tests. Until recently, this framework was technically very involved and represented computational challenges. These challenges have now been overcome, making Bayesian inference conceptually, technically, and computationally feasible for researchers across disciplines.
This workshop will introduce the logic of Bayesian inference and contrast it to null-hypothesis-significance-testing. After a brief conceptual introduction, the course will walk through a Bayesian statistical analysis using R and the package brms (Bürkner 2017), explaining how to set up a Bayesian regression model (including setting appropriate priors), how to test ‘hypotheses’ (including parameter estimation and Bayes factor), how to interpret the results, how to diagnose model convergence, and how to visualize and report the results. In hands-on exercises, the participants will immediately apply their knowledge to new data sets in R."

**Comment by jvcasillas** [comment]
I made a few minor edits to the second paragraph to make it sound like the labPhon ws isn't a one-off, i.e., This workshop > Our workshops. 

"Our workshops introduce the logic of Bayesian inference and contrast it to null-hypothesis-significance-testing. After providing a brief conceptual introduction, the course will walk through a Bayesian statistical analysis using R and the package brms (Bürkner 2017), explaining how to set up a Bayesian regression model (including setting appropriate priors), how to test 'hypotheses' (including parameter estimation and Bayes factor), how to interpret the results, how to diagnose model convergence, and how to visualize and report the results. In hands-on exercises, the participants will immediately apply their knowledge to new data sets in R."

**Comment by stefanocoretta** [comment]
I feel there's too much text. We might want to achieve a look close to this maybe

![image](https://user-images.githubusercontent.com/6429302/110851973-0f744600-82b2-11eb-9c6e-222bbd8327d1.png)

**Comment by jvcasillas** [comment]
I like this a lot. Sleek design and it seems to lend itself to what we want. Is it a different hugo template? (side note: i'm starting to dispise a lot of the hugo templates).

**Comment by stefanocoretta** [comment]
It's not a Hugo theme but we could easily find a plain html theme that is seminar or make one. We can switch back to a Hugo theme later on. And yes, most themes are irritating. Some are also not at all aesthetically pleasing.

**Comment by stefanocoretta** [comment]
https://tympanus.net/codrops/2014/07/14/freebie-halcyon-days-one-page-website-template/

**Comment by jvcasillas** [comment]
I agree about there being a lot of text. A simple solution (for now, unless we decide on a different template/framework) would be to put the first paragraph on the "about" page and leave the second paragraph on the landing page.

**Comment by stefanocoretta** [comment]
I made a prototype here: <https://learnb4ss.github.io/sandbox/>. Need to be filled with graphics and stuff.

**Comment by jvcasillas** [comment]
I think this is 100x better. If @troettge is on board, I say we go with this layout. Only real downside is that it's pure HTML/CSS, but I like it.

**Comment by troettge** [comment]
I like it. If we go for it, I can make a list of suggestions for the design

**Comment by stefanocoretta** [comment]
Great! if you guys agree, I'll move the current website to a different branch (so we can put it back later if we want) and put the new one in the root dir. (@jvcasillas Pure HTML/CSS might actually be an upside :D )

@troettge Suggest away!

**Comment by jvcasillas** [comment]
Sounds good. 👍🏼 

I agree HTML/css is probably better/more flexible, but i was just think about ease access so that any of the three of us can update. I also like the idea of being able to create blogposts in a way that is semi-automated (for the same reason), though Indont know if we even need/want a blog. Maybe that's something github discussions or slack or discord will be better for.

**Comment by troettge** [comment]
blog is not something I am personally interested in, I do see the accessibility issue, but if we just get a landing page going, there is probably only little that needs changed. Design suggestion incoming soon

**Comment by troettge** [comment]
- take out menu (top right), we just want a landing page right?
- need color scheme, how about: 
- ![image](https://user-images.githubusercontent.com/13022447/111025611-7cd4c380-83e5-11eb-970f-ef36237cc629.png)
- I like super accessible buttons leading to the main functionality of a landing page (currently "back to the article"). If you have an idea what that could be, I am all yours. If not, I'd say get rid of button.
- background banner? I really don't know what to put there. We could simply do a banner style with our hexagon logo, in bottom right akin to the banners I created for the many analyses google forms.
- The funky 80s thing, I'd use for advertizing but not on the webpage (background for the section "Do you want to learn bayesian data analysis" could just be a uniform color.
- I like the "why bayesian" thing. I figure the text blurbs are only stand-ins? Need icons for that as well.
- The workshop is fin as is. Maybe stronger contrast for the text. Also never ever use central alignment for text, it's difficult to read, either use justification (block) or left alignment.
- I like the team thing. What are the filled black points doing or supposed to do? Could get rid of them and hyperlink our photo to our websites. I'd suggest black/white photos maybe?
- subscribe thing: I'd say get rid of. But we could have a get in touch contact information. 
- Whats still missing is prominently displaying the dates and maybe link to a preparation page that walks them through the stuff that they need to do to be brms operational.

**Comment by stefanocoretta** [comment]
My idea was to use the one-page landing page for pre-workshop publicity and then switch back to hugo when/if we need blogging capabilities.

P.S. Note that this was just a prototype so there are spurious/missing elements, missing styling, etc...

**Comment by jvcasillas** [comment]
This all seems reasonable to me. 👍🏼

**Comment by stefanocoretta** [comment]
@troettge can you send me the hex codes of the colour palette, bitte?

**Comment by troettge** [comment]
that German bitte is slightly passive aggressive :D

haha I would have to pull it out of the .png myself. Will do when I have a spare moment

T

**Comment by stefanocoretta** [comment]
Is it??? But I've been told to always put _bitte_ in anything I ask! Oh boy... Anyway, no probs, I'll get the codes :)

**Comment by stefanocoretta** [comment]
@jvcasillas @troettge can you send me or link me to a portrait pic of you that looks good in B&W?

**Comment by jvcasillas** [comment]
Im going to consider this temporary because I can't find anything better right now. 

![jvc2021b](https://user-images.githubusercontent.com/1747068/111039404-e95abd00-83fb-11eb-9bae-91bc2906fd3d.png)
